version: '3.7'
services:
    postgres:                                           # create postgres container
        image: postgres:9.6
        container_name: postgres_container
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        networks: 
            aws_emr_tkit:
                ipv4_address: "10.0.100.10"

    airflow:                                # create airflow container
        build: './airflow_docker'           # construct the container along the Dockerfile in this folder
        container_name: airflow_container
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:                                        # mount the following local folders
            - ./dags:/usr/local/airflow/dags
        ports:
            - "8080:8080"                               # expose port
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
        networks: 
            aws_emr_tkit:
                ipv4_address: "10.0.100.80"

networks: 
  aws_emr_tkit:
    ipam: 
      driver: default
      config: 
        - subnet: 10.0.100.0/24